
package webservice_wsdl;

import webservice_wsdl.ObjectFactory;
import webservice_wsdl.StringBuffer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceImpl", targetNamespace = "http://webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns webservice.StringBuffer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://webservice/", className = "webservice.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://webservice/", className = "webservice.SayHelloResponse")
    @Action(input = "http://webservice/WebServiceImpl/sayHelloRequest", output = "http://webservice/WebServiceImpl/sayHelloResponse")
    public StringBuffer sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
